### ISSUE TITLE
Please remove the word Bluemix from the "getting started" page graphic

### ISSUE THREAD

**Issue by RogerSnook** [ibm-cloud-docs/SecureGateway#24] opened 2019-06-25 17:29 UTC

**Comment by ceciliachoi** [comment] 2019-09-02 09:28
The issue is fixed now:
<img width="1033" alt="51dbb000-ac94-11e9-9e39-ee815eb8cf0f" src="https://user-images.githubusercontent.com/41613417/64104570-0b0acb00-cda7-11e9-8e6c-0b824a5f99ac.png">
Thank you.

**Closed by ceciliachoi** 2019-09-02 09:28 UTC
